# -- 코드를 입력하세요
SELECT
    DISTINCT USER_ID, PRODUCT_ID
FROM
    (
    SELECT
        *, 
        ROW_NUMBER() OVER(PARTITION BY USER_ID, PRODUCT_ID ORDER BY SALES_DATE ASC) AS CNT
    FROM ONLINE_SALE
    ) AS temp
WHERE temp.CNT >= 2
ORDER BY 1 ASC, 2 DESC