-- 코드를 작성해주세요
SELECT
    CONCAT(QUARTER, "Q") AS QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM(
    SELECT 
        *, QUARTER(DIFFERENTIATION_DATE) AS QUARTER
    FROM ECOLI_DATA
) AS temp
GROUP BY 1
ORDER BY 1;