WITH ITEM_ALL AS(
    SELECT * FROM ITEM_INFO
    NATURAL JOIN ITEM_TREE
)

SELECT
    pre.ITEM_ID, pre.ITEM_NAME, pre.RARITY
FROM ITEM_ALL pre
INNER JOIN ITEM_ALL parent
ON pre.PARENT_ITEM_ID = parent.ITEM_ID
WHERE parent.RARITY = 'RARE'
ORDER BY 1 DESC