-- 코드를 작성해주세요
WITH RARE AS(
    SELECT
        ITEM_ID
    FROM ITEM_INFO 
    WHERE RARITY = "RARE"
)

SELECT
    ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO ii
INNER JOIN ITEM_TREE it
ON ii.ITEM_ID = it.ITEM_ID
WHERE it.PARENT_ITEM_ID IN (
                        SELECT ITEM_ID FROM RARE
                    )
ORDER BY 1 DESC