-- 코드를 작성해주세요
SELECT
    YEAR(temp2.DIFFERENTIATION_DATE) AS YEAR,
    (temp2.YEAR_MAX - temp2.SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM(
    SELECT
        *,
        MAX(temp.SIZE_OF_COLONY) OVER(PARTITION BY YEAR(temp.DIFFERENTIATION_DATE)) AS YEAR_MAX
    FROM ECOLI_DATA temp
) as temp2
ORDER BY 1, 2 ASC;