-- 코드를 입력하세요
SELECT
    CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK b
INNER JOIN BOOK_SALES bs
ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 1
ORDER BY 1 ASC