SELECT
    temp.CATEGORY, temp.PRICE AS MAX_PRICE, temp.PRODUCT_NAME
FROM(
    SELECT
        *, 
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('국', '김치', '과자', '식용유')
    ) AS temp
WHERE temp.PRICE_RANK = 1
ORDER BY 2 DESC